#!/bin/bash
#
# Input JSON from STDIN
# {
#   "source": {
#     "url": "https://kubernetes-charts.suse.com/",
#     "release_name": "suse/cf"
#   },
#   "version": { "ref": "61cebf" }
# }

set -e
IFS=" "

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

parse_source_config

output_single_version() {
  cat >&3 <<EOF
[
  { "ref": "$1" }
]
EOF
}

output_empty_list() {
  cat >&3 <<EOF
[]
EOF
}

helm init --client-only >/dev/null 2>&1
helm repo add $REPO_NAME $URL >/dev/null 2>&1
helm repo update >/dev/null 2>&1

CHART_VERSIONS=($(helm search $REPO_NAME/$RELEASE_NAME -l | tail -n +2 | awk '{ print $2 }' | xargs echo))
LATEST_CHART_VERSION="${CHART_VERSIONS[0]}"

if [ -z "$LATEST_CHART_VERSION" ]; then

  output_empty_list

else 

  output_single_version $LATEST_CHART_VERSION

fi
