#!/bin/bash
#
# Input JSON from STDIN
# {
#   "source": {
#     "bucket": "test",
#     "bucket_subfolder": "subfoo/",
#     "filter": "zip",
#     "aws_access_key_id": "xxxx",
#     "aws_secret_access_key": "yyy",
#     "aws_default_region": "us-east-1",
#   },
#   "version": { "ref": "file.zip" }
# }

set -e
IFS=" "

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

parse_source_config

output_single_version() {
  cat >&3 <<EOF
[
  { "ref": "$1" }
]
EOF
}

output_empty_list() {
  cat >&3 <<EOF
[]
EOF
}

if [ -n "$FILTER" ]; then
  KEY=$(aws s3 ls s3://$BUCKET/$BUCKET_DIR --recursive | grep "${FILTER}" | sort | tail -n 1 | awk '{print $4}')
else
  KEY=$(aws s3 ls s3://$BUCKET/$BUCKET_DIR --recursive | sort | tail -n 1 | awk '{print $4}')
fi

pushd $(mktemp -d /tmp/resource-check.XXXXXX)
aws s3 cp s3://$BUCKET/$KEY ./
               
FILE=$(ls)
echo $FILE
VERSION="$(date -r "$FILE" "+%Y-%m-%d %H:%M:%S")"

if [ -z "$VERSION" ]; then

  output_empty_list

else 

  output_single_version "$VERSION"

fi
