#!/bin/sh
#
# Input JSON from STDIN
# {
#   "source": {
#     "url": "https://kubernetes-charts.suse.com/",
#     "release_name": "suse/cf"
#   },
#   "version": { "ref": "61cebf" }
# }

set -e
IFS=" "

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

payload=$(mktemp /tmp/resource-in.XXXXXX)
cat > $payload <&0

parse_source_config

DESTINATION_DIR=$1

cd $DESTINATION_DIR

export HELM_REPO="$URL"
if [ -z "$VERSION" ] || [ "$VERSION" == "latest" ]; then
  $(dirname $0)/dist.sh
  else
  $(dirname $0)/dist.sh "$VERSION"
fi

VERSION=$(cat dist_version)
CHART_FILE=$(ls *.zip)
cat >&3 <<EOF
{
  "version": { "ref": "$VERSION" },
  "metadata": [
    { "name": "comment", "value": "$CHART_FILE" }
  ]
}
EOF